package main

const (
	COMMAND_NEWSITE             = "NEWSITE"
	COMMAND_UPDATESITE          = "UPDATESITE"
	COMMAND_GETSITEPROPERTY     = "GETSITEPROPERTY"
	COMMAND_LISTSOURCEPAGES     = "LISTSOURCEPAGES"
	COMMAND_EXPORTSOURCEPAGES   = "EXPORTSOURCEPAGES"
	COMMAND_LISTOUTPUTPAGES     = "LISTOUTPUTPAGES"
	COMMAND_LISTPAGE            = "LISTPAGE"
	COMMAND_COMPILE             = "COMPILE"
	COMMAND_HELP                = "HELP"
	COMMAND_CREATEMARKDOWN      = "CREATEMARKDOWN"
	COMMAND_ADDPAGE             = "ADDPAGE"
	COMMAND_UPDATEPAGE          = "UPDATEPAGE"
	COMMAND_DELETEPAGE          = "DELETEPAGE"
	COMMAND_LISTRECYCLEDPAGES   = "LISTRECYCLEDPAGES"
	COMMAND_RESTORERECYCLEDPAGE = "RESTORERECYCLEDPAGE"
	COMMAND_CLEARRECYCLEDPAGES  = "CLEARRECYCLEDPAGES"
	COMMAND_ADDFILE             = "ADDFILE"
	COMMAND_DELETEFILE          = "DELETEFILE"
	COMMAND_LISTFILE            = "LISTFILE"
)
